### ISSUE TITLE
FacebookController.java line 163 crash

### ISSUE THREAD

**Issue by alxmllr** [parse-community/ParseFacebookUtils-Android#45]
Hi.

Since our last app release we are getting an error (see stack below) whenever our users udpate the app. The package version si 1.12.0.

Is anyone else having this issue?

Fatal Exception: java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/util/Collection;Ljava/util/Collection;Lcom/facebook/AccessTokenSource;Ljava/util/Date;Ljava/util/Date;)V in class Lcom/facebook/AccessToken; or its super classes (declaration of 'com.facebook.AccessToken' appears in base.apk)
       at com.parse.FacebookController.setAuthData(FacebookController.java:163)
       at com.parse.ParseFacebookUtils$1.onRestore(ParseFacebookUtils.java:113)
       at com.parse.ParseAuthenticationManager$2.call(ParseAuthenticationManager.java:70)
       at com.parse.ParseAuthenticationManager$2.call(ParseAuthenticationManager.java:67)
       at bolts.Task$4.run(Task.java:357)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

**Comment by LOG-TAG** [comment]
@alxmllr how do you solved it? got an error after updating latest AS ? gradle plugin?
